server:
  port: 8000


spring:
  datasource:
    url: jdbc:mysql://10.211.55.3:3306/oa?useUnicode=true
    username: root
    password: 123456
mybatis:
  mapper-locations:
    classpath:  mappers/**/*.xml
